apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shubhscluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: key20
   - name: ng2
     desiredCapacity: 3
     instanceType: t2.small
     ssh:
        publicKeyName: key20
  